--- #YAML:1.0
name:               Lyrics-Fetcher
version:            0.5.2
abstract:           Perl extension to manage fetchers of song lyrics.
author:
    - David Precious <davidp@preshweb.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
